name = "todo-app"
specification = "A simple Todo List application that allows users to add, edit, mark as complete, and delete tasks. The application is developed using a Svelete as frontend and Go as backend to store the state.\nSpecifications:\n1. Tasks should be displayed in a list view\n2. Option to add a new task\n3. Option to edit a task\n4. Option to mark tasks as complete/incomplete\n5. Option to delete tasks\n6. Include unit tests for components and logic\n7. Use modern CSS components for cleaner UI\n\nNotes:\n- Use go 1.19\n- Use `github.com/vedhavyas/todo` as the go module name"

[files]
  ".eslintrc.js" = false
  ".github/workflows/cd.yml" = false
  ".github/workflows/ci.yml" = false
  ".gitignore" = false
  ".prettierrc" = false
  Dockerfile = false
  "README.md" = false
  "backend/api.go" = false
  "backend/api_test.go" = false
  "backend/store.go" = false
  "backend/store_test.go" = false
  "backend/task.go" = false
  "backend/task_test.go" = false
  "docker-compose.yml" = false
  "frontend/package.json" = false
  "frontend/public/build/bundle.css" = false
  "frontend/public/build/bundle.css.map" = false
  "frontend/public/build/bundle.js" = false
  "frontend/public/build/bundle.js.map" = false
  "frontend/public/favicon.ico" = false
  "frontend/public/global.css" = false
  "frontend/public/index.html" = false
  "frontend/rollup.config.js" = false
  "frontend/src/App.svelte" = false
  "frontend/src/components/DeleteTask.svelte" = false
  "frontend/src/components/EditTask.svelte" = false
  "frontend/src/components/MarkComplete.svelte" = false
  "frontend/src/components/MarkIncomplete.svelte" = false
  "frontend/src/components/NewTask.svelte" = false
  "frontend/src/components/Task.svelte" = false
  "frontend/src/components/TaskList.svelte" = false
  "frontend/src/main.js" = false
  "frontend/src/store/tasks.js" = false
  "frontend/src/store/tasks.test.js" = false
  "frontend/src/styles/deleteTask.css" = false
  "frontend/src/styles/editTask.css" = false
  "frontend/src/styles/global.css" = false
  "frontend/src/styles/markComplete.css" = false
  "frontend/src/styles/markIncomplete.css" = false
  "frontend/src/styles/newTask.css" = false
  "frontend/src/styles/task.css" = false
  "frontend/src/styles/taskList.css" = false
  "go.mod" = false
  "go.sum" = false
  "main.go" = false
